apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
